export const images = {
  bgWhiteBlur: '/images/CoffeeDetail/bgWhiteBlur.avif',
  logo: '/logo_tc_store.png',
  logoStore: '/logo_tc_store.png',
  logoVCB:
    'https://play-lh.googleusercontent.com/hRq2DVKkzBXQkyftxr0e2ytl0fS2hEWx3UTe3V652RfJVYWqVRGgBNhmZgqNzJ8PKHE',
  footer: {
    iconAddress: '/images/Footer/iconAddress.png',
    iconGmail: '/images/Footer/iconGmail.png',
    iconNumberPhone: '/images/Footer/iconNumberPhone.png',
    iconGithub: '/images/Footer/iconGitHub.png',
    iconLinkedin: '/images/Footer/iconLinkedin.png',
    iconFace: '/images/Footer/iconFace.png',
    iconYoutube: '/images/Footer/iconYoutobe.png',
    iconIntagram: '/images/Footer/iconIntagram.png',
    iconTitok: '/images/Footer/iconTiktok.png',
    iconZalo: '/images/Footer/iconZalo.png',
    iconGPS: '/images/Footer/iconGPS.png',
  },
  landingPage: {
    logo: '/images/LandingPage/Logo.webp',
    product2: '/images/LandingPage/product2.webp',
    coffee1: '/images/LandingPage/imagesCoffe.webp',
  },
  home: {
    logo: '/images/Home/logo.jpg',
    iconElement: '/images/Home/iconElement.png',
    iconOrigin: '/images/Home/iconOrigin.png',
    iconSmell: '/images/Home/smell.png',
    banner: {
      btnSlider: '/images/Home/Banner/iconBtnPositionControl.png',
      btnPositionActive: '/images/Home/Banner/bgBtnPositionItemInfo2Actived.png',
      btnPositionUnActive: '/images/Home/Banner/bgBtnPositionItemInfo2UnActive.png',
      bannerNest: '/images/Home/Banner/bannerNest.webp',
      bannerNest2: '/images/Home/Banner/bannerNest2.webp',
      bannerLaptop2: '/images/Home/Banner/bannerLaptop2.webp',
      bannerLaptop: '/images/Home/Banner/bannerlaptop.webp',
      bannerCoffee: '/images/Home/Banner/bannerCoffe.webp',
    },
  },
  icon: {
    iconHome: '/images/Icon/iconHome.png',
    iconMyUser: '/images/Icon/iconMyUser.png',
    iconLoadingModal: '/images/Icon/iconLoadingModal.png',
    iconCheckBoxSelected: '/images/Icon/iconCheckBoxSelected.svg',
    iconCheckBox: '/images/Icon/iconCheckBox.svg',
    iconOptionPayment: '/images/Icon/iconOptionPayment.png',
    iconMomo: '/images/Icon/iconMomo.png',
    iconWarning: '/images/Icon/iconWarning.png',
    iconDiscount: '/images/Icon/iconDiscount.png',
    iconBill: '/images/Icon/iconBill.webp',
    iconHistory: '/images/Icon/iconHistory.png',
    iconOrder: '/images/Icon/iconOrder.png',
    iconBack: '/images/Icon/iconBack.png',
    iconCart: '/images/Icon/iconCart.png',
    iconShield: '/images/Icon/iconShield.png',
    iconSupport: '/images/Icon/iconSupport.webp',
    iconResponsibility: '/images/Icon/iconResponsibility.webp',
    iconHeart: '/images/Icon/iconHeart.png',
    iconHeart1: '/images/Icon/iconHeart1.png',
    avatarDefault: '/images/Icon/avatarDefault.png',
    iconUpdating: '/images/Icon/iconUpdating.webp',
    iconSuccess: '/images/Icon/iconSuccess.png',
    iconShoppe: '/images/Icon/iconShoppe.png',
    iconZalo: '/images/Icon/iconZalo.png',
    messenger: '/images/Icon/iconMessager.png',
    iconDelete: '/images/Icon/iconDelete.png',
    iconFacebook: '/images/Icon/iconFaboook.png',
    iconChecked: '/images/Icon/iconChecked.png',
    iconSuccessGif: '/images/Icon/iconSuccess.gif',
    unknowTokenIcon: '/images/Icon/unknowTokenIcon.png',
    iconMessageChat: '/images/Icon/iconMessageChat.png',
  },
  userDetail: {
    iconUserDetail: '/images/Profile/Userdetail/iconUserDetail.png',
  },
  passkey: {
    bg: '/images/passkey/bg.png',
    bgMobile: '/images/passkey/bgMobile.png',
  },
}

export const imageConfig = {
  home: {
    bg: '/images/Home/bg.webp',
  },
}
